# -*- coding: utf-8 -*-
"""run_A1_A2_on_colab_1(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUU1IE4yuvkcSNpk-58UkM_fdcicspPr
"""



"""# CSG520 — Leaf disease project: A1 + A2 on Colab

Run the cells in order. **Before anything else: Runtime -> Change runtime type -> T4 GPU.**

Estimated wall clock on a T4: A2 ~25 min, A1 ~1.5 h per backbone.

## 1. Check the GPU
"""

!nvidia-smi
import torch
print("torch", torch.__version__, "| cuda available:", torch.cuda.is_available())

"""## 2. Mount Drive and keep outputs there

Colab wipes local disk when the runtime dies. Pointing `outputs/` at Drive means
checkpoints, metrics and figures survive a disconnect.
"""

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p /content/drive/MyDrive/csg520_outputs

!nproc

"""## 3. Upload and unzip the code

Run the cell, then pick `leaf_xai_A1_A2.zip` from your machine.
(Alternative: put the zip in Drive and use the commented line instead.)
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
from google.colab import files
uploaded = files.upload()          # choose leaf_xai_A1_A2.zip

# --- or, if the zip is already in Drive: ---
# !cp /content/drive/MyDrive/leaf_xai_A1_A2.zip /content/

!unzip -oq leaf_xai_A1_A2.zip
# %cd /content/leaf_xai
!ls -R | head -25

"""Send outputs to Drive instead of local disk:"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/leaf_xai
!rm -rf outputs && ln -s /content/drive/MyDrive/csg520_outputs outputs
!ls -ld outputs

"""## 4. Install the two packages Colab lacks

torch, torchvision, numpy, pandas, scikit-learn, scikit-image and matplotlib are
already on Colab. Only OpenCV's headless build and joblib may need a nudge.
"""

!pip install -q opencv-python-headless joblib
import cv2, skimage, sklearn, joblib
print("cv2", cv2.__version__, "| skimage", skimage.__version__, "| sklearn", sklearn.__version__)

"""## 5. Get PlantVillage

Easiest route is the Kaggle API. Get `kaggle.json` from your Kaggle account page
(Settings -> API -> Create New Token), then run this cell and upload it.

If you already have the dataset in Drive, skip to the cell after next.
"""

from google.colab import files
print("upload kaggle.json")
files.upload()

!mkdir -p ~/.kaggle && cp kaggle.json ~/.kaggle/ && chmod 600 ~/.kaggle/kaggle.json
!pip install -q kaggle

# Verify the slug on kaggle.com before running -- dataset slugs change.
!kaggle datasets download -d abdallahalidev/plantvillage-dataset -p /content/pv --unzip

"""Already have it in Drive? Use this instead of the cell above:"""

# !mkdir -p /content/pv && unzip -q /content/drive/MyDrive/plantvillage.zip -d /content/pv

"""## 6. Point `data/raw` at the class folders

PlantVillage ships `color/`, `grayscale/` and `segmented/` variants. We want
`color/`. This cell finds it (or any folder that looks like an ImageFolder root)
and symlinks it -- no copying 54k files around.
"""

# Commented out IPython magic to ensure Python compatibility.
import pathlib, os

SEARCH_ROOT = pathlib.Path('/content/pv')

def looks_like_class_root(p: pathlib.Path) -> int:
    """Number of immediate subdirectories that actually contain images."""
    if not p.is_dir():
        return 0
    n = 0
    for d in list(p.iterdir())[:60]:
        if d.is_dir() and any(f.suffix.lower() in {'.jpg', '.jpeg', '.png'}
                              for f in list(d.iterdir())[:5]):
            n += 1
    return n

# Prefer a folder literally named 'color'; otherwise take the richest candidate.
candidates = [p for p in SEARCH_ROOT.rglob('*') if p.is_dir()]
colour_dirs = [p for p in candidates if p.name.lower() == 'color']
best = colour_dirs[0] if colour_dirs else max(candidates, key=looks_like_class_root)
n_classes = looks_like_class_root(best)
print("using:", best, "|", n_classes, "class folders")
assert n_classes >= 2, "Could not locate the class folders -- check /content/pv by hand"

# %cd /content/leaf_xai
!rm -rf data/raw
os.symlink(best, '/content/leaf_xai/data/raw')
!ls data/raw | head -5

!ls outputs/metrics/

!grep -c "_scratch" src/approach1_transfer.py

"""## 7. Build the shared split (run once)

Writes `data/splits.csv` and `data/classes.json`. Every approach reads these,
which is what keeps A1 and A2 comparable. Do not rerun with `--force` later --
that reshuffles the split and invalidates any results you already have.
"""

# %cd /content/leaf_xai
# !python src/data.py --build --summary

"""## 8. Approach 2 — sanity pass first

Small and fast: confirms segmentation, feature extraction and both models run
before you commit to the full extraction.
"""

!python src/approach2_handcrafted.py --quick --max-per-class 60 --n-jobs 2 --perm-repeats 2 --segmentation-figure

"""Check the segmentation figure before going further. If the masks miss the brown
necrotic leaves badly, say so in the report rather than pretending otherwise.
"""

from IPython.display import Image, display
display(Image('outputs/figures/a2_segmentation.png'))

"""## 9. Approach 2 — the real run

Colab gives 2 vCPUs, so extraction is the slow part (~10-15 min for 400 images
per class). Features are cached to `outputs/features/*.npz`, so rerunning the
models afterwards costs nothing.
"""

# !python src/approach2_handcrafted.py --max-per-class 400 --n-jobs 2 2>&1 | tee outputs/a2_log.txt

!python src/approach2_handcrafted.py --max-per-class 400 --n-jobs 2 --skip-rf 2>&1 | tee outputs/a2_svm_log.txt

!python src/approach2_handcrafted.py --max-per-class 400 --n-jobs 2 --skip-svm 2>&1 | tee outputs/a2_rf_log.txt

"""## 10. Approach 1 — EfficientNet-B0 first

B0 is the faster backbone, so run it first: if something is wrong with the data
you find out in 5 minutes instead of an hour.
"""

!python src/approach1_transfer.py --arch efficientnet_b0 --workers 2 2>&1 | tee outputs/a1_effnet_log.txt

!cp data/splits.csv data/classes.json /content/drive/MyDrive/csg520_outputs/

"""## 11. Approach 1 — ResNet50"""

!python src/approach1_transfer.py --arch resnet50 --epochs 8 --workers 2 2>&1 | tee outputs/a1_resnet_log.txt

"""## 12. The ablation that answers A1's question

Same architecture, random initialisation instead of ImageNet weights. Capped per
class so it finishes quickly -- for a fair comparison, run the pretrained version
with the **same** cap:

    python src/approach1_transfer.py --arch resnet50 --max-per-class 500

Then compare macro-F1 *and* the two Grad-CAM figures.
"""

import pathlib

p = pathlib.Path('src/approach1_transfer.py')
s = p.read_text()

if '_scratch' in s:
    print('already patched, nothing to do')
else:
    edits = [
        ('    print(f"[a1] device={device}  amp={use_amp}  arch={args.arch}")',
         '    print(f"[a1] device={device}  amp={use_amp}  arch={args.arch}")\n\n'
         '    tag = f"a1_{args.arch}" + ("_scratch" if args.no_pretrained else "")\n'
         '    args.tag = tag'),
        ('    ckpt_path = config.CKPT_DIR / f"a1_{args.arch}.pt"',
         '    ckpt_path = config.CKPT_DIR / f"{tag}.pt"'),
        ('    utils.save_metrics(metrics, f"a1_{args.arch}")',
         '    utils.save_metrics(metrics, tag)'),
        ('    utils.plot_confusion_matrix(y_true, y_pred, classes, f"a1_{args.arch}_confusion")',
         '    utils.plot_confusion_matrix(y_true, y_pred, classes, f"{tag}_confusion")'),
        ('        utils.plot_training_curves(history, f"a1_{args.arch}_curves")',
         '        utils.plot_training_curves(history, f"{tag}_curves")'),
        ('        run_gradcam(model, loaders, classes, args.arch, device)',
         '        run_gradcam(model, loaders, classes, args.arch, device, tag=tag)'),
        ('def run_gradcam(model, loaders, classes, arch: str, device, n_images: int = 8) -> None:',
         'def run_gradcam(model, loaders, classes, arch: str, device, n_images: int = 8,\n'
         '                tag: str | None = None) -> None:'),
        ('        out_name=f"a1_{arch}_gradcam",',
         '        out_name=f"{tag or f\'a1_{arch}\'}_gradcam",'),
        ('    (config.METRIC_DIR / f"a1_{args.arch}_history.json").write_text(',
         '    (config.METRIC_DIR / f"{getattr(args, \'tag\', f\'a1_{args.arch}\')}_history.json").write_text('),
    ]
    for old, new in edits:
        assert s.count(old) == 1, f'NO MATCH: {old[:60]}'
        s = s.replace(old, new)
    p.write_text(s)
    print('patched OK')

# !python src/approach1_transfer.py --arch resnet50 --no-pretrained --max-per-class 500 --workers 2 2>&1 | tee outputs/a1_scratch_log.txt
# !python src/approach1_transfer.py --arch resnet50 --no-pretrained --warmup-epochs 0 --epochs 11 --workers 2 2>&1 | tee outputs/a1_scratch_log.txt
!python src/approach1_transfer.py --arch resnet50 --no-pretrained --warmup-epochs 0 --epochs 11 --workers 12 2>&1 | tee outputs/a1_scratch_log.txt



!python src/approach1_transfer.py --arch resnet50 --no-pretrained --eval-only --workers 2

import json, pathlib
p = pathlib.Path('outputs/metrics/a1_resnet50.json')
m = json.load(p.open())
m['pretrained'] = True
json.dump(m, p.open('w'), indent=2)
print('fixed')

"""GO BACK AND RUN SVM

## 13. Look at the figures
"""

from IPython.display import Image, display
import glob, os

for path in sorted(glob.glob('outputs/figures/*.png')):
    print(os.path.basename(path))
    display(Image(path))

"""## 14. Collect the numbers for the results table"""

from IPython.display import Image, display
display(Image('outputs/figures/a1_resnet50_scratch_gradcam.png'))
display(Image('outputs/figures/a1_resnet50_scratch_curves.png'))

import json, glob, os
import pandas as pd

rows = []
for path in sorted(glob.glob('outputs/metrics/a*.json')):
    if path.endswith('_history.json'):
        continue
    m = json.load(open(path))
    if 'accuracy' not in m:
        continue
    rows.append({
        'run': os.path.basename(path).replace('.json', ''),
        'approach': m.get('approach'),
        'model': m.get('architecture') or m.get('model'),
        'pretrained': m.get('pretrained', '-'),
        'accuracy': round(m['accuracy'], 4),
        'balanced_acc': round(m['balanced_accuracy'], 4),
        'macro_F1': round(m['macro_f1'], 4),
        'test_n': m['n_samples'],
    })

table = pd.DataFrame(rows)
table.to_csv('outputs/metrics/summary_table.csv', index=False)
table

import json, glob, os
import pandas as pd

rows = []
for path in sorted(glob.glob('outputs/metrics/a*.json')):
    if path.endswith('_history.json'):
        continue
    m = json.load(open(path))
    if 'accuracy' not in m:
        continue
    rows.append({
        'run': os.path.basename(path).replace('.json', ''),
        'approach': m.get('approach'),
        'model': m.get('architecture') or m.get('model'),
        'pretrained': m.get('pretrained', '-'),
        'accuracy': round(m['accuracy'], 4),
        'balanced_acc': round(m['balanced_accuracy'], 4),
        'macro_F1': round(m['macro_f1'], 4),
        'test_n': m['n_samples'],
    })

table = pd.DataFrame(rows)
table.to_csv('outputs/metrics/summary_table.csv', index=False)
table

import numpy as np, config
cm = np.loadtxt('outputs/metrics/a1_resnet50_confusion_counts.csv', delimiter=',').astype(int)
classes = config.load_classes()

err = [(cm[i, j], classes[i], classes[j], int(cm[i].sum()))
       for i in range(len(classes)) for j in range(len(classes))
       if i != j and cm[i, j] > 0]

for c, t, p, n in sorted(err, reverse=True):
    print(f'{c:2d} of {n:4d}   {t:52s} -> {p}')
print('\ntotal errors:', sum(e[0] for e in err), '| pairs:', len(err))

"""## 15. Download everything

Outputs are already in Drive (`MyDrive/csg520_outputs`). This just gives you a
local zip too.
"""

!cd /content && zip -rq results.zip /content/drive/MyDrive/csg520_outputs
from google.colab import files
files.download('/content/results.zip')

"""## If the runtime disconnects mid-training

The best checkpoint so far is already in Drive, so nothing is lost, but training
does not resume from where it stopped. Options:

- Score what you have: `!python src/approach1_transfer.py --arch resnet50 --eval-only`
- Restart with a shorter schedule: `--epochs 8`
- Or cap the data: `--max-per-class 800`

Keep the tab open and the machine awake; free Colab disconnects an idle session
after roughly 90 minutes.
"""